#!/bin/bash

method_names=(
  # "bandgap-gpt35-sel1k"
  # "co2_perm-gpt35-sel1k"
  # "cs-gpt35-sel1k"
  # "ct-gpt35-sel1k"
  # "dc-gpt35-sel1k"
  # "density-gpt35-sel1k"
  # "eab-gpt35-sel1k"
  # "fs-gpt35-sel1k"
  # "hardness-gpt35-sel1k"
  # "h2_perm-gpt35-sel1k"
  # "iec-gpt35-sel1k"
  # "ionic_cond-gpt35-sel1k"
  # "is-gpt35-sel1k"
  # "lcst-gpt35-sel1k"
  "loi-gpt35-sel1k"
  "methanol_perm-gpt35-sel1k"
  "o2_perm-gpt35-sel1k"
  "ri-gpt35-sel1k"
  "sd-gpt35-sel1k"
  "tc-gpt35-sel1k"
  "td-gpt35-sel1k"
  "tm-gpt35-sel1k"
  "ts-gpt35-sel1k"
  "tg-gpt35-sel1k"
  "ucst-gpt35-sel1k"
  "wca-gpt35-sel1k"
  "wu-gpt35-sel1k"
  "ym-gpt35-sel1k"
)

para_subsets=(
  "bandgap-ner-sel1k-no-unit"
  "co2_perm-ner-sel1k-no-unit"
  "cs-ner-sel1k-no-unit"
  "ct-ner-sel1k-no-unit"
  "dc-ner-sel1k-no-unit"
  "density-ner-sel1k-no-unit"
  "eab-ner-sel1k-no-unit"
  "fs-ner-sel1k-no-unit"
  "hardness-ner-sel1k-no-unit"
  "h2_perm-ner-sel1k-no-unit"
  "iec-ner-sel1k-no-unit"
  "ionic_cond-ner-sel1k-no-unit"
  "is-ner-sel1k-no-unit"
  "lcst-ner-sel1k-no-unit"
  "loi-ner-sel1k-no-unit"
  "methanol_perm-ner-sel1k-no-unit"
  "o2_perm-ner-sel1k-no-unit"
  "ri-ner-sel1k-no-unit"
  "sd-ner-sel1k-no-unit"
  "tc-ner-sel1k-no-unit"
  "td-ner-sel1k-no-unit"
  "tm-ner-sel1k-no-unit"
  "ts-ner-sel1k-no-unit"
  "tg-ner-sel1k-no-unit"
  "ucst-ner-sel1k-no-unit"
  "wca-ner-sel1k-no-unit"
  "wu-ner-sel1k-no-unit"
  "ym-ner-sel1k-no-unit"
)

property_names=(
  "bandgap"
  "CO2 permeability"
  "compressive strength or compressive modulus"
  "crystallization temperature or Tc"
  "dielectric constant or relative permittivity"
  "density"
  "elongation at break"
  "flexural strength or bend strength or modulus of rupture or transverse rupture strength"
  "hardness"
  "hydrogen or H2 permeability"
  "ion exchange capacity or iec"
  "proton conductivity or ionic conductivity or hydroxide conductivity or OH^{-} conductivity"
  "impact strength"
  "lower critical solution temperature"
  "limiting oxygen index"
  "methanol permeability"
  "oxygen or O2 permeability"
  "refractive index"
  "swelling degree"
  "thermal conductivity"
  "thermal decomposition temperature or thermal stability or Td"
  "melting temperature"
  "tensile strength or ultimate strength"
  "glass transition temperature or Tg"
  "upper critical solution temperature"
  "water contact angle"
  "water uptake"
  "youngs modulus"
)

nohup_folder="/data/sonakshi/PromptDataExtraction/filtered_paras/nohup/sel1k"
chmod +w "$nohup_folder"

for i in "${!method_names[@]}"; do
    method_name="${method_names[i]}"
    filter_name="${para_subsets[i]}"
    property_name="${property_names[i]}"
    log_file="${method_name}.log"
    output_file="${nohup_folder}/${method_name}-${filter_name}.out"

    echo "Running ner pipeline for: $method_name with filter: $filter_name"
    nohup python backend method new -m "$method_name" --filter "$filter_name" --dataset data1 --model gpt-3.5-turbo --api openai --info user sonakshi --info shot_selector random --info n_shots 1 --info api_retry_delay 60 --info delay_multiplier 0.5 --info max_api_retries 1 --info api_request_delay 0.01 --info temperature 0.001 --info  prompt "Extract all $property_name values in JSONL format with 'material', 'property', 'value', 'condition' columns." --info shot_nrecords 2 --info shot_keywords false > "$output_file" 2>&1 &
done